development:
  adapter: postgresql
  host: localhost
  database: vdash_development
  username: vdash
  password: vdash
test:
  adapter: postgresql
  host: localhost
  database: vdash_test
  username: vdash

production:
  adapter: postgresql
  host: localhost
  database: vdash_production
  username: vdash
